databases:
  - name: management
    plan: free
    databaseName: mysite
    user: mysite

services:
  - type: web
    plan: free
    name: lcs-web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'gunicorn lcs.wsgi:application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: management
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4